# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  rgName: 'F365C'
  location: 'uksouth'
  templateFile: 'CA Monitoring/Bicep/main.bicep'
  azureserviceconnection: 'F365-ServiceConnection'
  subscriptionid: '9bcfadfd-8b9a-407b-974c-de3b4e51ee91'
  kvname: 'CAMonitoring-Keyvault'


pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: '$(subscriptionid)'
    KeyVaultName: '$(kvname)'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy VM Bicep
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureserviceconnection)'
    subscriptionId: '$(subscriptionid)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(rgName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: '-adminUsername 'adminPipeline' -adminPassword $(adminPassword)'
    deploymentMode: 'Incremental'
    # deploymentOutputs: 'asp-json'
    
